/*
 * generated by Xtext
 */
package linear.algebra.matrix.ui.contentassist

import linear.algebra.matrix.ui.contentassist.AbstractMatrixProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MatrixProposalProvider extends AbstractMatrixProposalProvider {
}
