/*
* generated by Xtext
*/
package linear.algebra.matrix;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MatrixStandaloneSetup extends MatrixStandaloneSetupGenerated{

	public static void doSetup() {
		new MatrixStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public void register(Injector injector) {
		// added after the switching to Xcore
		if (!EPackage.Registry.INSTANCE.containsKey("http://linear.algebra/matrix/Matrix"))
			EPackage.Registry.INSTANCE.put("http://linear.algebra/matrix/Matrix", linear.algebra.matrix.matrix.MatrixPackage.eINSTANCE);
		super.register(injector);
    }
}

