/*
* generated by Xtext
*/
package linear.algebra.matrix;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MatrixStandaloneSetup extends MatrixStandaloneSetupGenerated{

	public static void doSetup() {
		new MatrixStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

