/*
 * generated by Xtext
 */
package linear.algebra.matrix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MatrixUiModule extends linear.algebra.matrix.ui.AbstractMatrixUiModule {
	public MatrixUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return MatrixEObjectHoverProvider.class;
	}
}
