/*
 * generated by Xtext
 */
package linear.algebra.matrix.validation

import linear.algebra.matrix.typing.validation.XSemanticMatrixValidator

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class MatrixValidator extends XSemanticMatrixValidator {
}
